name: Create GitHub Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: release
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        uses: heitorpolidoro/auto-release@v1
        with:
          update_released_versions: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}